---
name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install pipenv
        shell: bash
        run: pipx install pipenv

      - run: pipenv requirements --exclude-markers > requirements.txt
      - run: mkdir dependencies
      - run: mkdir dependencies/python
      - run: docker run --rm \        
            --volume=$(pwd):/lambda-build \
            -w=/lambda-build \
            lambci/lambda:build-python3.8 \
            pip install -r requirements.txt --target dependencies/python
      - run: terraform apply