---
name: Terraform plan
on:
  pull_request:
  workflow_dispatch:

jobs:
  tf_plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Install pipenv
        shell: bash
        run: pipx install pipenv

      - run: pipenv requirements --exclude-markers > requirements.txt
      - run: mkdir dependencies
      - run: mkdir dependencies/python
      - run: docker run --rm --volume=$(pwd):/lambda-build -w=/lambda-build lambci/lambda:build-python3.8 pip install -r requirements.txt --target dependencies/python

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: eu-west-2

      - uses: dflook/terraform-plan@50b375f84b6c68c386d78ca53b2af6067eea3d7c # v1.29.1
        with:
          path: terraform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
